name: survey_flutter_ic
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.2
  flutter_riverpod: ^2.3.1
  freezed_annotation: ^2.2.0
  japx: ^2.0.4
  go_router: ^6.2.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  package_info_plus: ^3.0.3
  permission_handler: ^10.2.0
  retrofit: ^4.0.1
  riverpod_annotation: ^2.0.1
  get_it: ^7.2.0
  fluttertoast: ^8.2.1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mockito: ^5.2.0
  retrofit_generator: ^6.0.0+1
  test: ^1.12.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - test_resource/fake_response/

  fonts:
    - family: neuzeit
      fonts:
        - asset: assets/fonts/neuzeit_normal.otf
          weight: 400
        - asset: assets/fonts/neuzeit_bold.otf
          weight: 800

flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml
